version: '3.8'

services:
  server:
    build:
      context: . 
      dockerfile: Dockerfile
    volumes:
      - ./html:/usr/src/app/html
    ports:
      - "8080:80"

  playwright:
    image: mcr.microsoft.com/playwright:v1.48.0-focal
    volumes:
      - ./tests:/app/tests 
      - ./package.json:/app/package.json 
      - ./package-lock.json:/app/package-lock.json 
    working_dir: /app 
    environment:
      BASE_URL: http://server:8080
    command: sh -c "npm install && npx playwright test && tail -f /dev/null" 